import os
Import('env')

prog = env.Program('tests', Glob("*.cpp"), LIBS=['gtest', 'gtest_main', 'mem', 'util'], 
                                           LIBPATH=['#inst/lib'], 
                                           CXXFLAGS=['-DGTEST_USE_OWN_TR1_TUPLE=1'], 
                                           CPPPATH=["#inst/include"])

env.Alias("install", env.Install(os.path.join(env['PREFIX'], "bin"), prog))

