import os
Import('env')

prog = env.Library('util', Glob("*.cpp"), CPPPATH=["#inst/include"])

env.Alias("install", env.Install(os.path.join(env['PREFIX'], "include", "util"), Glob("*.h")))
env.Alias("install", env.Install(os.path.join(env['PREFIX'], "lib"), prog))

